import type { ServiceId } from "./types";

export const APP_VERSION = "1.0.0";
export const TIMEZONE = "Eastern Time (Newport, TN)";

export const BUSINESS = {
  name: "REB Gunsmithing",
  tagline: "Precision. Safety. Craftsmanship.",
  address: "1424 Lower English Creek Rd., Newport, TN 37821",
  mobile: "704-340-0197",
  mobileTel: "tel:7043400197",
  office: "423-237-0200",
  officeTel: "tel:4232370200",
  owner: "Rich Bryant",
  ownerTitle: "Owner / Certified Gunsmith",
  maps: "https://maps.google.com/?q=1424+Lower+English+Creek+Rd,+Newport,+TN+37821",
};

export const CREDENTIALS = [
  "AGI Certified Gunsmith",
  "AGI Certified Master Armorer",
  "AGI Certified Firearms Appraiser",
  "GLOCK Certified Armorer",
] as const;

export const MORE_CREDENTIALS = [
  "AGI Certified 1911 Pistolsmith",
  "AGI Certified Red Dot Installer",
  "AGI Certified Law Enforcement AR-15 Armorer",
  "FFL Licensed",
] as const;

export const DISCLAIMER =
  "This is a preliminary, visual-only assessment generated by AI. It cannot detect internal damage, wear or safety defects. Internal issues require an in-person inspection by a certified gunsmith. Do not rely on this result to decide whether a firearm is safe to fire.";

export const SAFETY_REMINDER =
  "Make sure the firearm is unloaded and the action is open or safe before photographing. Never handle a firearm in a way that is unsafe.";

export const POLICY_ACK =
  "I will transport the firearm safely and legally, unloaded, and in accordance with local law. I will not bring ammunition to the shop.";

export const STATUS_LABEL: Record<string, string> = {
  pending: "Pending",
  confirmed: "Confirmed",
  in_progress: "In Progress",
  ready: "Ready for Pickup",
  completed: "Completed",
  cancelled: "Cancelled",
  submitted: "Submitted",
  reviewing: "Under Review",
  quoted: "Quote Sent",
  scheduled: "Scheduled",
  closed: "Closed",
  draft: "Draft",
  under_review: "Under Review",
  assessed: "Assessed by Gunsmith",
  good: "Good",
  minor: "Minor",
  attention: "Needs Attention",
  standard: "Standard",
  priority: "Priority",
};

export const SERVICE_ORDER: ServiceId[] = ["cleaning", "repair", "inspection", "appraisal"];

export const ANGLES = [
  { id: "left", label: "Left side", tip: "Fill the frame with the full side. Keep the muzzle pointed in a safe direction." },
  { id: "right", label: "Right side", tip: "Match the left-side distance so both sides can be compared." },
  { id: "top", label: "Top", tip: "Show the top of the receiver and barrel. Avoid overhead glare." },
  { id: "muzzle", label: "Muzzle / barrel exterior", tip: "Photograph the outside of the muzzle. Do not look down the bore and do not include ammunition." },
  { id: "action", label: "Action / receiver exterior", tip: "Show the outside of the action. Leave it open only if you already know how to do that safely." },
  { id: "stock", label: "Stock / grip", tip: "Include chips, cracks, or worn checkering if they are visible." },
  { id: "marks", label: "Markings (optional)", tip: "Manufacturer marks only. Cover the serial number if you do not want it in the photo." },
  { id: "damage", label: "Visible damage close-up", tip: "Move closer to scratches, dents, or rust. This step can be skipped if nothing stands out." },
] as const;

export const CANNED_REPLIES = [
  "Thanks for the note. Please bring the firearm unloaded at your appointment time.",
  "I reviewed the photos. I will need to see it in the shop before I can comment on function.",
  "Your appointment is confirmed. A reminder will be sent the day before.",
  "The work is finished and the firearm is ready for pickup during shop hours.",
];
